# Generated by Django 3.0.5 on 2020-04-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_sighting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='cat',
            new_name='cryptid',
        ),
        migrations.AlterField(
            model_name='sighting',
            name='date',
            field=models.DateField(verbose_name='Date of sighting'),
        ),
    ]
